apiVersion: templates.gatekeeper.sh/v1
kind: AllowOperators
metadata:
  name: allow-some-operators
spec:
  operators:
    - "openshift-cert-manager-operator.default"
    namespaces:
    - "allowed-namespace"
