apiVersion: constraints.gatekeeper.sh/v1beta1
kind: OperatorAllowList
metadata:
  name: my-operator-allow-list
spec:
  match:
    kinds:
      - apiGroups: ["operators.coreos.com"]
        kinds: ["Subscription"]
    namespaces:
      - "keith-operator-test"
  parameters:
    allowedOperators:
      - "nginx-ingress-operator"
    allowedSources:
      - "certified-opeators"
