apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: allowoperators
spec:
  crd:
    spec:
      names:
        kind: AllowOperators
      validation:
        openAPIV3Schema:
          type: object
          properties:
            operators:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package allowoperators

        violation[{"msg": msg}] {
          input.request.kind.kind == "ClusterServiceVersion"
          input.request.operation == "CREATE"
          allowed := data.allowoperators.operators
          msg := sprintf("The operator %v is not allowed to be installed.", [input.request.object.metadata.name])
          not input.request.object.metadata.name in allowed
        }
