apiVersion: constraints.gatekeeper.sh/v1beta1
kind: OperatorAllowList
metadata:
  name: tenantb-operator-allow-list
spec:
  match:
    kinds:
      - apiGroups: ["operators.coreos.com"]
        kinds: ["Subscription"]
    namespaces:
      - "tenantb"
  parameters:
    allowedOperators:
      - "mongodb-operator"
    allowedSources:
      - "community-operators"
