apiVersion: constraints.gatekeeper.sh/v1beta1
kind: OperatorAllowList
metadata:
  name: tenanta-operator-allow-list
spec:
  match:
    kinds:
      - apiGroups: ["operators.coreos.com"]
        kinds: ["Subscription"]
    namespaces:
      - "tenanta"
  parameters:
    allowedOperators:
      - "nginx-ingress-operator"
    allowedSources:
      - "certified-operators"
