apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operatorhub-view-keith
  namespace: keith-operator-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operatorhub-config-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: keith
